name: Read index.html

on: 
  push: 
     branches: 
           -main

jobs:
   read-file:
      runs-on: ubuntu-latest


     steps:
        -name: Checkout repository
         uses: actions/checkout@v3

        -name: Print index.html contents
         run:  cat index.html
